In [15]:
import numpy as np

In [33]:
b = np.arange(12).reshape(4,3)
print(b)



c = np.arange(4)
print(np.c_[b,c])


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


ValueError: ignored

In [ ]:
import numpy as np
from scipy import stats
a = np.random.randint(3,size=(5,5))
print(a,"\n\n")
c = stats.mode(a,axis=1,keepdims=True)
print(c)
print(c[0].T[0])


b = np.argsort(a)
print(b)
print(b<3)


[[0 1 2 0 0]
 [0 0 0 1 2]
 [1 0 1 0 0]
 [2 0 1 1 2]
 [0 0 0 2 2]] 


ModeResult(mode=array([[0],
       [0],
       [0],
       [1],
       [0]]), count=array([[3],
       [3],
       [3],
       [2],
       [3]]))
[0 0 0 1 0]
[[0 3 4 1 2]
 [0 1 2 3 4]
 [1 3 4 0 2]
 [1 2 3 0 4]
 [0 1 2 3 4]]
[[ True False False  True  True]
 [ True  True  True False False]
 [ True False False  True  True]
 [ True  True False  True False]
 [ True  True  True False False]]


In [ ]:
import numpy as np
w = np.arange(16).reshape(4,4)
print(w)

print(w[:,2])
print(w[2,2]/(np.sum(w[:,2])-w[2,2]))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 2  6 10 14]
0.45454545454545453


In [ ]:
a = np.array([[1,9,5,4],
        [2,9,8,5],
        [6,7,2,4]])
print(a**2)

[[ 1 81 25 16]
 [ 4 81 64 25]
 [36 49  4 16]]
